# Generated by Django 3.2.10 on 2021-12-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20211228_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="course_runner_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_completed",
            field=models.BooleanField(default=False),
        ),
    ]
