# Generated by Django 6.0.1 on 2026-01-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_enrollment_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="buddy",
            field=models.ManyToManyField(blank=True, to="users.profile"),
        ),
    ]
