# Generated by Django 3.2.10 on 2021-12-24 13:52

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_auto_20211207_1124"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="body",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="slide",
            name="body",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
