# Generated by Django 3.2.10 on 2022-01-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('materials', '0005_section_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='stream',
            new_name='slides',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
