# Generated by Django 3.2.12 on 2022-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_auto_20220118_0145"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
