# Generated by Django 3.2.12 on 2022-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_auto_20220326_1633"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="topic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
