# Generated by Django 3.2.12 on 2022-03-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0013_alter_resource_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
