# Generated by Django 3.2.12 on 2022-03-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='topic',
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.ManyToManyField(to='materials.Topic'),
        ),
    ]
