# Generated by Django 3.2.12 on 2022-03-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0015_auto_20220328_0154"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="topic",
            new_name="topics",
        ),
    ]
