# Generated by Django 3.2.12 on 2022-10-05 02:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='tip_body',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='section',
            name='slides',
            field=wagtail.fields.StreamField([('resource', wagtail.blocks.StructBlock([('resource', wagtail.images.blocks.ImageChooserBlock())])), ('baseblock', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock())])), ('questionblock', wagtail.blocks.StructBlock([('question', wagtail.blocks.TextBlock()), ('choice_1', wagtail.blocks.TextBlock()), ('choice_2', wagtail.blocks.TextBlock()), ('choice_3', wagtail.blocks.TextBlock()), ('choice_4', wagtail.blocks.TextBlock()), ('correct', wagtail.blocks.ChoiceBlock(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]))])), ('headlineleftimage', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock()), ('heading', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('imagetopblock', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('imagerightblock', wagtail.blocks.StructBlock([('body', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))]),
        ),
    ]
