# Generated by Django 3.2.12 on 2022-10-12 19:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_auto_20221005_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slides',
            field=wagtail.fields.StreamField([('resource', wagtail.blocks.StructBlock([('resource', wagtail.images.blocks.ImageChooserBlock())])), ('baseblock', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True)), ('body', wagtail.blocks.RichTextBlock())])), ('questionblock', wagtail.blocks.StructBlock([('question', wagtail.blocks.TextBlock()), ('choice_1', wagtail.blocks.TextBlock()), ('explanation_1', wagtail.blocks.TextBlock()), ('choice_2', wagtail.blocks.TextBlock()), ('explanation_2', wagtail.blocks.TextBlock()), ('choice_3', wagtail.blocks.TextBlock()), ('explanation_3', wagtail.blocks.TextBlock()), ('choice_4', wagtail.blocks.TextBlock()), ('explanation_4', wagtail.blocks.TextBlock()), ('correct', wagtail.blocks.ChoiceBlock(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]))])), ('headlineleftimage', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('imagetopblock', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True)), ('body', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('imagerightblock', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(blank=True, max_length=200, null=True)), ('body', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))]),
        ),
    ]
